spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/controlescolar
    username: controlescolar
    password: controlescolar
  data:
    mongodb:
      uri: mongodb://localhost:27017/controlescolar
