-- Expediente del alumno (domicilio, discapacidad, lentes, tutor/responsable).
-- Alimenta también el apoyo estadístico 911.

CREATE TABLE domicilios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle varchar(160),
    numero_exterior varchar(20),
    numero_interior varchar(20),
    entre_calle varchar(120),
    y_calle varchar(120),
    colonia varchar(120),
    codigo_postal varchar(10),
    referencia varchar(240),
    localidad_id bigint REFERENCES localidades (id),
    municipio_id bigint REFERENCES municipios (id),
    estado_id bigint REFERENCES estados (id)
);

CREATE TABLE discapacidades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(20) NOT NULL UNIQUE,
    nombre varchar(120) NOT NULL
);

INSERT INTO discapacidades (codigo, nombre) VALUES
    ('MOTORA', 'Motriz'),
    ('VISUAL', 'Visual'),
    ('AUDITIVA', 'Auditiva'),
    ('INTELECTUAL', 'Intelectual'),
    ('PSICOSOCIAL', 'Psicosocial'),
    ('MULTIPLE', 'Múltiple'),
    ('OTRA', 'Otra');

ALTER TABLE alumnos ADD COLUMN sexo varchar(1);
ALTER TABLE alumnos ADD COLUMN fecha_nacimiento date;
ALTER TABLE alumnos ADD COLUMN usa_lentes boolean NOT NULL DEFAULT false;
ALTER TABLE alumnos ADD COLUMN usa_zapato_ortopedico boolean NOT NULL DEFAULT false;
ALTER TABLE alumnos ADD COLUMN domicilio_id bigint REFERENCES domicilios (id);

CREATE TABLE alumnos_discapacidades (
    alumno_id bigint NOT NULL REFERENCES alumnos (id),
    discapacidad_id bigint NOT NULL REFERENCES discapacidades (id),
    PRIMARY KEY (alumno_id, discapacidad_id)
);

ALTER TABLE tutores ADD COLUMN curp varchar(18);
ALTER TABLE tutores ADD COLUMN apellido_paterno varchar(80);
ALTER TABLE tutores ADD COLUMN apellido_materno varchar(80);
ALTER TABLE tutores ADD COLUMN parentesco varchar(40);
ALTER TABLE tutores ADD COLUMN telefono varchar(30);
ALTER TABLE tutores ADD COLUMN celular varchar(30);
ALTER TABLE tutores ADD COLUMN correo varchar(120);
ALTER TABLE tutores ADD COLUMN estudios varchar(80);
ALTER TABLE tutores ADD COLUMN ocupacion varchar(80);
ALTER TABLE tutores ADD COLUMN domicilio_id bigint REFERENCES domicilios (id);
ALTER TABLE tutores ADD COLUMN vive_con_alumno boolean NOT NULL DEFAULT true;

ALTER TABLE alumnos_tutores ADD COLUMN responsable boolean NOT NULL DEFAULT true;
