CREATE TABLE ciclos_escolares (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(40) NOT NULL UNIQUE,
    inicio date NOT NULL,
    fin date NOT NULL
);

CREATE TABLE calendarios_escolares (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ciclo_id bigint NOT NULL REFERENCES ciclos_escolares (id),
    nivel varchar(40) NOT NULL,
    institucion_id bigint REFERENCES instituciones (id),
    dias_efectivos integer,
    estado varchar(20) NOT NULL
);

CREATE UNIQUE INDEX calendarios_oficiales_uk
    ON calendarios_escolares (ciclo_id, nivel)
    WHERE institucion_id IS NULL;

CREATE TABLE eventos_calendario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendario_id bigint NOT NULL REFERENCES calendarios_escolares (id),
    tipo varchar(30) NOT NULL,
    nombre varchar(120) NOT NULL,
    inicio date NOT NULL,
    fin date NOT NULL
);

CREATE TABLE periodos_ciclo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendario_id bigint NOT NULL REFERENCES calendarios_escolares (id),
    periodo_plan_id bigint NOT NULL REFERENCES periodos_planes (id),
    orden integer NOT NULL,
    inicio date NOT NULL,
    fin date NOT NULL,
    estado varchar(20) NOT NULL
);

CREATE TABLE ventanas_captura (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_ciclo_id bigint NOT NULL REFERENCES periodos_ciclo (id),
    momento_evaluacion_id bigint NOT NULL REFERENCES momentos_evaluacion (id),
    captura_desde date NOT NULL,
    captura_hasta date NOT NULL,
    publicacion_desde date
);

CREATE TABLE planteles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(160) NOT NULL
);

ALTER TABLE instituciones ADD COLUMN plantel_id bigint REFERENCES planteles (id);
ALTER TABLE instituciones ADD COLUMN nivel varchar(40);

CREATE TABLE centros_trabajo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES instituciones (id),
    plantel_id bigint NOT NULL REFERENCES planteles (id),
    clave varchar(10) NOT NULL UNIQUE,
    nombre varchar(160) NOT NULL,
    entidad_clave varchar(2) NOT NULL,
    entidad_nombre varchar(80) NOT NULL,
    clasificador varchar(1) NOT NULL,
    sostenimiento varchar(30) NOT NULL,
    identificador varchar(2) NOT NULL,
    nivel varchar(30) NOT NULL,
    progresivo varchar(4) NOT NULL,
    verificador varchar(1) NOT NULL
);

ALTER TABLE usuarios ADD COLUMN centro_trabajo_id bigint REFERENCES centros_trabajo (id);

CREATE TABLE generaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES instituciones (id),
    nombre varchar(80) NOT NULL,
    anio_inicio integer NOT NULL
);

ALTER TABLE alumnos ADD COLUMN generacion_id bigint REFERENCES generaciones (id);
ALTER TABLE grupos ADD COLUMN generacion_id bigint REFERENCES generaciones (id);

CREATE TABLE asignaciones_docentes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES instituciones (id),
    grupo_id bigint NOT NULL REFERENCES grupos (id),
    profesor_id bigint NOT NULL REFERENCES profesores (id),
    asignatura_clave varchar(20) NOT NULL,
    UNIQUE (grupo_id, asignatura_clave, profesor_id)
);

ALTER TABLE horarios ADD COLUMN asignacion_id bigint REFERENCES asignaciones_docentes (id);

CREATE TABLE dictamenes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES instituciones (id),
    alumno_id bigint NOT NULL REFERENCES alumnos (id),
    tipo varchar(20) NOT NULL,
    dictamen_por varchar(40) NOT NULL,
    escuela_origen varchar(160) NOT NULL,
    ciclo_inicio varchar(20) NOT NULL,
    ciclo_fin varchar(20) NOT NULL,
    dependencia varchar(120),
    estado varchar(80),
    pais varchar(80),
    expediente varchar(40),
    folio varchar(40),
    promedio numeric(4, 1),
    fecha_expedicion date NOT NULL,
    materias varchar(500)
);

ALTER TABLE movimientos_alumnos ADD COLUMN fecha date;

ALTER TABLE calificaciones ADD COLUMN causa varchar(40);
ALTER TABLE calificaciones ADD COLUMN presentado boolean;
ALTER TABLE calificaciones ADD COLUMN orden_extra integer;

ALTER TABLE planes_versiones ADD COLUMN umbral_creditos integer;
ALTER TABLE planes_versiones ADD COLUMN esquema_editable boolean NOT NULL DEFAULT true;

INSERT INTO ciclos_escolares (nombre, inicio, fin)
VALUES ('2025-2026', DATE '2025-09-01', DATE '2026-07-15');

INSERT INTO permisos (codigo) VALUES ('DICTAMEN_CONSULTAR'), ('DICTAMEN_CAPTURAR');

INSERT INTO perfiles_permisos (perfil_id, permiso_id)
SELECT pp.perfil_id, nuevo.id
FROM perfiles_permisos pp
JOIN permisos origen ON origen.id = pp.permiso_id AND origen.codigo = 'INSCRIPCION_CAPTURAR'
JOIN permisos nuevo ON nuevo.codigo IN ('DICTAMEN_CONSULTAR', 'DICTAMEN_CAPTURAR');
