CREATE TABLE perfiles_plantilla (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(120) NOT NULL UNIQUE
);

CREATE TABLE perfiles_plantilla_permisos (
    perfil_plantilla_id bigint NOT NULL REFERENCES perfiles_plantilla (id),
    permiso_id bigint NOT NULL REFERENCES permisos (id),
    PRIMARY KEY (perfil_plantilla_id, permiso_id)
);
