CREATE TABLE institucion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(160) NOT NULL,
    clave_cct varchar(20),
    particular boolean NOT NULL,
    activa boolean NOT NULL
);

CREATE TABLE usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint REFERENCES institucion (id),
    login varchar(80) NOT NULL UNIQUE,
    clave varchar(120) NOT NULL,
    nombre varchar(160) NOT NULL
);

CREATE TABLE perfil (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint REFERENCES institucion (id),
    nombre varchar(80) NOT NULL
);

CREATE TABLE permiso (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(60) NOT NULL UNIQUE
);

CREATE TABLE perfil_permiso (
    perfil_id bigint NOT NULL REFERENCES perfil (id),
    permiso_id bigint NOT NULL REFERENCES permiso (id),
    PRIMARY KEY (perfil_id, permiso_id)
);

CREATE TABLE usuario_perfil (
    usuario_id bigint NOT NULL REFERENCES usuario (id),
    perfil_id bigint NOT NULL REFERENCES perfil (id),
    PRIMARY KEY (usuario_id, perfil_id)
);

CREATE TABLE institucion_modulo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    modulo varchar(40) NOT NULL,
    UNIQUE (institucion_id, modulo)
);
