CREATE TABLE plan_rector (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivel varchar(40) NOT NULL,
    nombre varchar(160) NOT NULL,
    tipo_periodo varchar(40) NOT NULL
);

CREATE TABLE plan_version (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_rector_id bigint NOT NULL REFERENCES plan_rector (id),
    numero integer NOT NULL,
    estado varchar(20) NOT NULL,
    minimo numeric(5, 2),
    maximo numeric(5, 2),
    aprobatoria numeric(5, 2),
    cualitativa boolean NOT NULL,
    reinscribe_sin_promedio boolean NOT NULL,
    max_materias_reprobadas integer
);

CREATE TABLE periodo_plan (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_version_id bigint NOT NULL REFERENCES plan_version (id),
    orden integer NOT NULL,
    nombre varchar(80) NOT NULL
);

CREATE TABLE momento_evaluacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_version_id bigint NOT NULL REFERENCES plan_version (id),
    orden integer NOT NULL,
    nombre varchar(80) NOT NULL,
    tipo varchar(30) NOT NULL,
    cuenta_promedio boolean NOT NULL
);

CREATE TABLE asignatura_plan (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_version_id bigint NOT NULL REFERENCES plan_version (id),
    clave varchar(20) NOT NULL,
    nombre varchar(160) NOT NULL,
    horas integer,
    creditos integer,
    optativa boolean NOT NULL,
    modulo varchar(80),
    submodulo varchar(80)
);

CREATE TABLE programa (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    plan_version_id bigint NOT NULL REFERENCES plan_version (id),
    nombre varchar(160) NOT NULL
);

CREATE TABLE anexo_version (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    programa_id bigint NOT NULL REFERENCES programa (id),
    numero integer NOT NULL,
    estado varchar(20) NOT NULL
);

CREATE TABLE asignatura_anexo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anexo_version_id bigint NOT NULL REFERENCES anexo_version (id),
    clave varchar(20) NOT NULL,
    nombre varchar(160) NOT NULL
);
