CREATE TABLE profesor (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    nombre varchar(160) NOT NULL
);

CREATE TABLE grupo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    programa_id bigint NOT NULL REFERENCES programa (id),
    nombre varchar(80) NOT NULL,
    periodo_orden integer NOT NULL
);

CREATE TABLE horario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    grupo_id bigint NOT NULL REFERENCES grupo (id),
    profesor_id bigint NOT NULL REFERENCES profesor (id),
    asignatura_clave varchar(20) NOT NULL,
    dia varchar(12) NOT NULL,
    hora_inicio varchar(5) NOT NULL,
    hora_fin varchar(5) NOT NULL
);
