CREATE TABLE estado (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(80) NOT NULL
);

CREATE TABLE municipio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado_id bigint NOT NULL REFERENCES estado (id),
    nombre varchar(80) NOT NULL
);

CREATE TABLE localidad (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id bigint NOT NULL REFERENCES municipio (id),
    nombre varchar(80) NOT NULL
);

CREATE TABLE alumno (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    curp varchar(18) NOT NULL,
    nombre varchar(80) NOT NULL,
    apellido_paterno varchar(80) NOT NULL,
    apellido_materno varchar(80),
    estatus varchar(20) NOT NULL,
    localidad_id bigint REFERENCES localidad (id),
    UNIQUE (institucion_id, curp)
);

CREATE TABLE tutor (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    nombre varchar(160) NOT NULL,
    usuario_id bigint REFERENCES usuario (id)
);

CREATE TABLE alumno_tutor (
    alumno_id bigint NOT NULL REFERENCES alumno (id),
    tutor_id bigint NOT NULL REFERENCES tutor (id),
    PRIMARY KEY (alumno_id, tutor_id)
);

CREATE TABLE inscripcion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    alumno_id bigint NOT NULL REFERENCES alumno (id),
    grupo_id bigint NOT NULL REFERENCES grupo (id),
    plan_version_id bigint NOT NULL REFERENCES plan_version (id),
    anexo_version_id bigint REFERENCES anexo_version (id),
    historica boolean NOT NULL
);

CREATE TABLE movimiento_alumno (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    alumno_id bigint NOT NULL REFERENCES alumno (id),
    tipo varchar(30) NOT NULL,
    detalle varchar(240) NOT NULL
);
