CREATE TABLE calificacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    alumno_id bigint NOT NULL REFERENCES alumno (id),
    plan_version_id bigint NOT NULL REFERENCES plan_version (id),
    asignatura_clave varchar(20) NOT NULL,
    periodo_orden integer NOT NULL,
    momento_id bigint NOT NULL REFERENCES momento_evaluacion (id),
    valor numeric(5, 2),
    observacion varchar(450),
    faltas integer,
    acta varchar(40),
    complementaria boolean NOT NULL,
    UNIQUE (alumno_id, asignatura_clave, periodo_orden, momento_id)
);
