CREATE TABLE lista_asistencia (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    grupo_id bigint NOT NULL REFERENCES grupo (id),
    fecha date NOT NULL,
    UNIQUE (grupo_id, fecha)
);

CREATE TABLE asistencia_alumno (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lista_id bigint NOT NULL REFERENCES lista_asistencia (id),
    alumno_id bigint NOT NULL REFERENCES alumno (id),
    presente boolean NOT NULL,
    UNIQUE (lista_id, alumno_id)
);

CREATE TABLE falta_profesor (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    profesor_id bigint NOT NULL REFERENCES profesor (id),
    fecha date NOT NULL
);
