CREATE TABLE documento_escolar (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    alumno_id bigint NOT NULL REFERENCES alumno (id),
    tipo varchar(20) NOT NULL,
    folio varchar(40) NOT NULL,
    fecha_emision date NOT NULL,
    archivo_id varchar(80) NOT NULL,
    UNIQUE (institucion_id, folio)
);

CREATE TABLE aviso (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint NOT NULL REFERENCES institucion (id),
    alumno_id bigint NOT NULL REFERENCES alumno (id),
    texto varchar(240) NOT NULL
);

CREATE TABLE auditoria_evento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id bigint,
    accion varchar(80) NOT NULL,
    detalle varchar(240) NOT NULL
);
